DROP TABLE IF EXISTS certificates CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS orders_certificates CASCADE;
DROP TABLE IF EXISTS tagged_certificates CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS users CASCADE;
